DROP TABLE MLT;
DROP TABLE MCT;
DROP TABLE Evenement;
DROP TABLE Messages;
DROP TABLE Conversation;
DROP TABLE Compagnon_Virtuel;
DROP TABLE Sujets_Sensibles;
DROP TABLE Preferences;
DROP TABLE Profil;
